### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by JaeSeoKim** [JaeSeoKim/react-kakao-maps-sdk#60]
- [ ] 번들 사이즈 다이어트
- [ ] e2e 테스트 추가 (vanila 버전과 react 버전 비교하는 형태로 만들기.!)
- [ ] example 제공 (간단한 서비스 형태로 제공하기.!)
  - [ ] vite
  - [ ] next.js
  - [] next.js-app #59
- [ ] 문서화 업데이트

**Comment by JaeSeoKim** [comment]
테스트 코드 샘플 추가 및 e2e에서 사용되는 sample 코드 docs와 연동, 기존 live-editor에서 sandpack으로 이전

**Comment by Dave352** [comment]
문서화에 참여할 수 있는 방법은 없을까요?

**Comment by JaeSeoKim** [comment]
@Dave352 언제든지 PR를 날려주시면 반영하도록 하겠습니다.!

문서화 참여에 대한 문서는 내일 저녁 내로 작성하여 공유해드리도록 하겠습니다.!

**Comment by red-dev-Mark** [comment]
@Dave352 안녕하세요 혹시 지금 Next15 + React19 신버전에서의 `Polyline`이 확인되지 않는 이슈는 없나요? `MapMarker`와 같이 다른 기능들은 잘 동작하는데 `Polyline`만 출력이 안 돼서요.!
